spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: main_server
    password: qwertyuiop
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
